### ISSUE TITLE
该标定算法有对应的理论吗？

### ISSUE THREAD

**Issue by luodanping** [BIT-MJY/Multiple_Lidar_Calibration#3]
你好，是采用基于平面约束的优化方案吗？

**Comment by BIT-MJY** [comment]
是的，通过在不同坐标系下拟合平面，进行平面的对齐，从而找到相对位姿关系。其中旋转使用法向量对齐，平移使用标定板质心对齐。这个程序是为了比赛速写的，一定会有更先进的标定理论，但是这个代码的标定效果已经不错了（我们自己测试了多次），所以就没在管它。

**Comment by luodanping** [comment]
好的，感谢。这个方法跟 autoware 的lidar-camera标定比较接近，使用法向量对齐求旋转初值，求平移时用的是面上的点与法向量垂直的约束，这就不要求完整拍摄标定板了。

再请教一个问题，“平移使用标定板质心对齐“，所以两个lidar都需要完整拍到标定板吗？不然质心对齐，不太对

**Comment by BIT-MJY** [comment]
感谢指出，使用质心对齐确实不是一个完美的解决方案，但是我们经过测试后发现效果还不错，就用了，可能跟标定行为有关。此外，我本来是想用质心对齐提供一个平移初始值再跟一个ICP、NDT，新版代码也加入了这一部分，但是还没完成。如果您有更好的标定方法的相关资料可以附上连接，谢谢～

**Comment by BIT-MJY** [comment]
感谢关注，由于没有后续讨论，此问题将关闭。

**Comment by luodanping** [comment]
您好，      您的邮件我已收到，我将尽快回复您。
