### ISSUE TITLE
平移分量标定不准确

### ISSUE THREAD

**Issue by Cxz-dev** [BIT-MJY/Multiple_Lidar_Calibration#4]
看到您在标平移分量时，CostFunction定义为质心距离之差，是否有考虑过定义为原点到平面的距离之差会更准确一点，期待回复！

**Comment by BIT-MJY** [comment]
感谢关注我们的工作！

您指的是激光雷达原点到平面质心的距离吗？如果严格按照xyz轴，即绕着质心标准旋转的话，二者在本质上是一样的，因此也会朝正确的方向标定，效果是否有显著提升可以尝试一下 :)

此外，如果发现平移不准确的情况，很有可能是阈值选取不合理造成的，见[此链接](https://github.com/BIT-MJY/Multiple_Lidar_Calibration/issues/1)

**Comment by Cxz-dev** [comment]
感谢您的回复！

我使用了激光雷达的原点到两个平面的距离之差作为costfunction以后，平移分量有±0.2左右的精度提升，这可能也和特定的标定数据有关。

再者，我发现在截取标定板点云的时候会有地面点的干扰导致标定不准确，我通过cloudcompare对点云进行了进一步的剪切，不知您还有更简洁有效的方法吗？

谢谢！

**Comment by BIT-MJY** [comment]
地面点云自动去除可以见我的另一个[分支](https://github.com/BIT-MJY/Multiple_Lidar_Calibration/tree/withGroundRemoval)

恭喜效果提升！本仓是为了给大家提供简洁有效、容易上手的标定方法，且有助于对ceres优化库的理解，如果您愿意的话，是否可以把您更改的版本提交上来呢？这样大家可以使用您优化后的代码，并且我会在readme里面注明您的更新内容和更新的作者。

如果您愿意，可以提交至分支[version1.2.1](https://github.com/BIT-MJY/Multiple_Lidar_Calibration/tree/version1.2.1)

**Comment by BIT-MJY** [comment]
由于长时间没有回复，此问题关闭，有后续问题可随时reopen。
