### ISSUE TITLE
关于平面法向量的问题

### ISSUE THREAD

**Issue by Student865** [BIT-MJY/Multiple_Lidar_Calibration#5]
您好！在用您的算法进行标定的时候，发现结果不太准确，于是一张一张的pcd来进行标定，于是发现了以下问题：某些结果差得特别离谱，于是我将副雷达在标定板上的点云按标定结果转换到了主雷达坐标系，惊奇的发现两者所在平面确实重合了。但应该是法向量方向相反的两个平面，导致旋转参数差了一定角度，平移量差距特别大。请问您在测试的时候遇到过这个结果吗，我该如何避免出现这样的情况呢？

**Comment by BIT-MJY** [comment]
感谢您使用我们的代码！

麻烦告知下雷达的类型、线束。

我们在使用时，发现标定不准的情况出现于平面阈值设置过小，见[此链接](https://github.com/BIT-MJY/Multiple_Lidar_Calibration/issues/1)。其他情况并未发现问题。

我在约束旋转的时候使用的是1-法向量夹角的余弦值作为残差，因此如果法向量相反，残差应该是处于最大的情况，会被优化掉。所以您说的很对！如果模型输出的法向量方向相反，将会导致错误优化。然而我对PCL拟合平面参数的机制并没有多少了解。

因此我建议使用函数[setAxis()](https://pointclouds.org/documentation/classpcl_1_1_s_a_c_segmentation.html#a23abc3e522ccb2b2846a6c9b0cf7b7d3)和
函数[setEpsAngle()](https://pointclouds.org/documentation/classpcl_1_1_s_a_c_segmentation.html#a7a2dc31039a1717f83ca281f6970eb18)对平面拟合的结果进行约束，前者将指定轴，后者指定模型法向量与指定轴的夹角，因此可能会去除法向量角度相反的情况。

本仓旨在为大家多雷达标定提供一个简单的baseline，有助于从源码角度理解最简单的标定原理，现在我可能没有时间优化代码，如果您有更好的想法，且修改了代码有更好的效果，欢迎contribution!

**Comment by Student865** [comment]
您好，我这边用的是两个速腾的rs16雷达。
感谢您的回复。我这边截出来的pcd图中标定板上只有2～4条点束，感觉可能也有一定关系，我这边会按照您的建议继续探究，如有疑问或者发现还会向您提出。
非常感谢帮助！

**Comment by BIT-MJY** [comment]
不客气。是的，这个是有影响的，可以适当移近标定板，保证更多线数。

**Comment by Student865** [comment]
您好，我的坐标转换的理论知识比较欠缺，目前对该标定原理有一些疑问。
在标定旋转参数的时候，我们以法向量夹角作为损失函数。但是，这样的话，会不会无法去约束标定板在其所在平面的旋转呢？也可以说是如何去约束标定板以其法向量为轴的旋转呢？这样会导致可能得到很多不同结果吗？
希望您不吝赐教，谢谢！

**Comment by BIT-MJY** [comment]
如果数据少可能会出现，我们采取使用多组不同标定板位姿来避免这种情况发生。

**Comment by BIT-MJY** [comment]
Closed
