### ISSUE TITLE
关于标定旋转时的误差函数

### ISSUE THREAD

**Issue by nothingbutanything** [BIT-MJY/Multiple_Lidar_Calibration#6]
您好！
在阅读您的代码时发现，您应该是在对第一张图进行标定后，将其结果作为标第二张的初值放入，并以此类推。
这样对单独每一张进行标定的话，是否会产生可以绕平面法向量旋转所带来的误差？
是否可以选择将所有36张图像的法向量夹角绝对值之和加起来作为法向量，再进行一次性的计算呢？
您当时单独进行，有什么其他的考虑吗？
希望您可以解答我的这些疑问。不胜感激`

**Comment by BIT-MJY** [comment]
感谢使用本代码！

代码中并非是一张一张标定的，而是逐次将所有的pair加入到了损失函数当中，然后每次循环迭代都标了此前所有的pair。
`for (int k=0; k<pcd_num_per_lidar; k++)`这个循环就是在不断的加入cost的，每次循环都进行`ceres::Solve`的优化解算。

**Comment by BIT-MJY** [comment]
由于长时间无回复，此问题关闭。若您有后续疑问可以重新开启本问题。
